version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "04:00"
  ignore:
  - dependency-name: node
    versions:
    - ">= 15.pre.alpine.a, < 16"
  - dependency-name: python
    versions:
    - ">= 3.9.a, < 3.10"
  rebase-strategy: disabled
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: weekly
    day: saturday
    time: "04:00"
  ignore:
  - dependency-name: "@date-io/date-fns"
    versions:
    - "> 1.3.13"
  - dependency-name: node-sass
    versions:
    - "> 4.14.1"
  rebase-strategy: disabled
- package-ecosystem: pip
  directory: "/backend"
  schedule:
    interval: weekly
    day: saturday
    time: "04:00"
  ignore:
  - dependency-name: django
    versions:
    - ">= 3.2.a, < 3.3"
  rebase-strategy: disabled
