version: 2
updates:
  # Docker
  - package-ecosystem: docker
    directory: '/'
    target-branch: 'development'
    schedule:
      interval: weekly
      day: saturday
      time: '04:00'
    rebase-strategy: disabled

  # Javascript
  - package-ecosystem: npm
    directory: '/frontend'
    target-branch: 'development'
    schedule:
      interval: weekly
      day: saturday
      time: '04:00'
    rebase-strategy: disabled

  # Python
  - package-ecosystem: pip
    directory: '/backend'
    target-branch: 'development'
    schedule:
      interval: weekly
      day: saturday
      time: '04:00'
    rebase-strategy: disabled

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'development'
    schedule:
      interval: weekly
      day: saturday
      time: '04:00'
