env:
  browser: true
  es6: true
extends:
  - airbnb
  - prettier
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:prettier/recommended
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - .
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules:
  {
    'prettier/prettier': ['error', { 'endOfLine': 'auto' }],
    'react/forbid-prop-types': 'off',
    'react/jsx-no-useless-fragment': ['error', { 'allowExpressions': true }],
    'react/no-unstable-nested-components': ['error', { 'allowAsProps': true }],
    'react/react-in-jsx-scope': 'off',
  }
