env:
  browser: true
  es6: true
extends:
  - airbnb
  - prettier
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:prettier/recommended
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - .
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules:
  {
    'prettier/prettier': ['error', { 'endOfLine': 'auto' }],
    'react/forbid-prop-types': 0,
    'react/jsx-uses-react': 'off',
    'react/react-in-jsx-scope': 'off',
  }
