# Generated by Django 3.1.13 on 2021-09-30 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("video_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(common.models.get_sentinel_user),
                related_name="requested_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
