# Generated by Django 3.2.12 on 2022-02-25 15:55

from django.db import migrations


def set_requested_by(apps, schema_editor):
    Request = apps.get_model("video_requests", "Request")
    for request in Request.objects.all():
        if not request.requested_by:
            request.requested_by = request.requester
            request.save()


class Migration(migrations.Migration):
    dependencies = [
        ("video_requests", "0002_add_request_requested_by"),
    ]

    operations = [
        migrations.RunPython(set_requested_by),
    ]
