# Generated by Django 3.2.12 on 2022-02-25 15:59

from django.conf import settings
from django.db import migrations, models

import common.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("video_requests", "0003_update_request_requested_by_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=models.SET(common.models.get_sentinel_user),
                related_name="requested_by_user",
                to="auth.user",
            ),
        ),
    ]
