# Generated by Django 3.2.13 on 2022-05-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_requests", "0004_alter_request_requested_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcomment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical comment",
                "verbose_name_plural": "historical comments",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrating",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical rating",
                "verbose_name_plural": "historical ratings",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrequest",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical request",
                "verbose_name_plural": "historical requests",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalvideo",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical video",
                "verbose_name_plural": "historical videos",
            },
        ),
        migrations.AlterField(
            model_name="historicalcomment",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalrating",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalrequest",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalvideo",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
