# Generated by Django 5.0.2 on 2024-03-04 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("video_requests", "0005_bump_simple_history_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Nyitva"), (2, "Lezárva"), (3, "Elvetve")],
                        default=1,
                    ),
                ),
                (
                    "assignees",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=models.SET(common.models.get_sentinel_user),
                        related_name="todo_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to="video_requests.request",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to="video_requests.video",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
