# Generated by Django 6.0.3 on 2026-03-26 00:07

from django.conf import settings
from django.db import migrations, models

import common.models


class Migration(migrations.Migration):

    dependencies = [
        ("video_requests", "0006_add_todos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrequest",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Elutasítva"),
                    (1, "Felkérés"),
                    (2, "Elvállalva"),
                    (3, "Leforgatva"),
                    (4, "Beírva"),
                    (5, "Megvágva"),
                    (6, "Archiválva"),
                    (7, "Lezárva"),
                    (9, "Szervezők által lemondva"),
                    (10, "Meghiúsult"),
                ],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="historicalvideo",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Vágásra vár"),
                    (2, "Vágás alatt"),
                    (3, "Megvágva"),
                    (4, "Kikódolva"),
                    (5, "Közzétéve"),
                    (6, "Lezárva"),
                ],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=models.SET(common.models.get_sentinel_user),
                related_name="submitted_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="requester",
            field=models.ForeignKey(
                on_delete=models.SET(common.models.get_sentinel_user),
                related_name="requested_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(common.models.get_sentinel_user),
                related_name="responsible_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Elutasítva"),
                    (1, "Felkérés"),
                    (2, "Elvállalva"),
                    (3, "Leforgatva"),
                    (4, "Beírva"),
                    (5, "Megvágva"),
                    (6, "Archiválva"),
                    (7, "Lezárva"),
                    (9, "Szervezők által lemondva"),
                    (10, "Meghiúsult"),
                ],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Vágásra vár"),
                    (2, "Vágás alatt"),
                    (3, "Megvágva"),
                    (4, "Kikódolva"),
                    (5, "Közzétéve"),
                    (6, "Lezárva"),
                ],
                db_index=True,
                default=1,
            ),
        ),
    ]
