# Generated by Django 5.0.2 on 2024-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_requests", "0006_add_todos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Nyitva"), (2, "Lezárva"), (3, "Elvetve")], default=1
            ),
        ),
    ]
