# Generated by Django 6.0.3 on 2026-03-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_requests", "0007_add_status_index_fix_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Nyitva"), (2, "Lezárva"), (3, "Elvetve")],
                db_index=True,
                default=1,
            ),
        ),
    ]
