[tool.flake8]
max-line-length = 88
max-complexity = 15
ignore = ["E203", "E501", "W503"]
per-file-ignores = [
    "backend/core/settings/*.py: F403,F405",
    "backend/common/apps.py: F401",
    "backend/video_requests/apps.py: F401"
]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings.test"
python_files = "tests.py test_*.py *_tests.py"
python_classes= ""

[tool.coverage.run]
branch = true
source = ["."]

[tool.coverage.report]
fail_under = 90
ignore_errors = true
show_missing = true
skip_covered = true
omit = [
    "core/*",
    "tests/*",
    "*/migrations/*",
    "*/admin.py",
    "*/tests.py",
    "common/health_checks.py",
    "manage.py",
]
exclude_lines = [
    "pragma: no cover",
    "if settings.DEBUG",
    'if getattr.*"swagger_fake_view".*',
    "return .*[.]none[(][)]]",
]
