/* tslint:disable */
/* eslint-disable */
/**
 * BSS Request Manager API
 * REST API for Workflow Support System for managing video shooting, filming and live streaming requests of Budavári Schönherz Stúdió.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: kecskemety.oliver@simonyi.bme.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PatchedRequestAdminUpdateRequest
 */
export interface PatchedRequestAdminUpdateRequest {
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  additional_data?: { [key: string]: any };
  /**
   *
   * @type {string}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  deadline?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  end_datetime?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  place?: string;
  /**
   *
   * @type {number}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  requester?: number;
  /**
   *
   * @type {string}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  requester_email?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  requester_first_name?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  requester_last_name?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  requester_mobile?: string;
  /**
   *
   * @type {number}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  responsible?: number | null;
  /**
   *
   * @type {string}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  start_datetime?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof PatchedRequestAdminUpdateRequest
   */
  type?: string;
}
