/* tslint:disable */
/* eslint-disable */
/**
 * BSS Request Manager API
 * REST API for Workflow Support System for managing video shooting, filming and live streaming requests of Budavári Schönherz Stúdió.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kecskemety.oliver@simonyi.bme.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { TodoNestedRequestVideo } from './todo-nested-request-video';
// May contain unused imports in some cases
// @ts-ignore
import { UserNestedList } from './user-nested-list';

/**
 *
 * @export
 * @interface TodoAdminListRetrieve
 */
export interface TodoAdminListRetrieve {
  /**
   *
   * @type {Array<UserNestedList>}
   * @memberof TodoAdminListRetrieve
   */
  assignees: Array<UserNestedList>;
  /**
   *
   * @type {string}
   * @memberof TodoAdminListRetrieve
   */
  created: string;
  /**
   *
   * @type {UserNestedList}
   * @memberof TodoAdminListRetrieve
   */
  creator: UserNestedList;
  /**
   *
   * @type {string}
   * @memberof TodoAdminListRetrieve
   */
  description: string;
  /**
   *
   * @type {number}
   * @memberof TodoAdminListRetrieve
   */
  id: number;
  /**
   *
   * @type {TodoNestedRequestVideo}
   * @memberof TodoAdminListRetrieve
   */
  request: TodoNestedRequestVideo;
  /**
   *
   * @type {number}
   * @memberof TodoAdminListRetrieve
   */
  status: number;
  /**
   *
   * @type {TodoNestedRequestVideo}
   * @memberof TodoAdminListRetrieve
   */
  video: TodoNestedRequestVideo;
}
