/* tslint:disable */
/* eslint-disable */
/**
 * BSS Request Manager API
 * REST API for Workflow Support System for managing video shooting, filming and live streaming requests of Budavári Schönherz Stúdió.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kecskemety.oliver@simonyi.bme.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserNestedDetail
 */
export interface UserNestedDetail {
  /**
   *
   * @type {string}
   * @memberof UserNestedDetail
   */
  avatar_url: string;
  /**
   *
   * @type {string}
   * @memberof UserNestedDetail
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof UserNestedDetail
   */
  full_name: string;
  /**
   *
   * @type {number}
   * @memberof UserNestedDetail
   */
  id: number;
  /**
   *
   * @type {boolean}
   * @memberof UserNestedDetail
   */
  is_staff: boolean;
  /**
   *
   * @type {string}
   * @memberof UserNestedDetail
   */
  phone_number: string;
}
