/* tslint:disable */
/* eslint-disable */
/**
 * BSS Request Manager API
 * REST API for Workflow Support System for managing video shooting, filming and live streaming requests of Budavári Schönherz Stúdió.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kecskemety.oliver@simonyi.bme.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
  /**
   *
   * @type {any}
   * @memberof UserProfile
   */
  avatar: any;
  /**
   *
   * @type {string}
   * @memberof UserProfile
   */
  avatar_url: string;
  /**
   *
   * @type {string}
   * @memberof UserProfile
   */
  phone_number?: string;
}
