/* tslint:disable */
/* eslint-disable */
/**
 * BSS Request Manager API
 * REST API for Workflow Support System for managing video shooting, filming and live streaming requests of Budavári Schönherz Stúdió.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kecskemety.oliver@simonyi.bme.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { RatingRetrieve } from './rating-retrieve';

/**
 *
 * @export
 * @interface VideoListRetrieve
 */
export interface VideoListRetrieve {
  /**
   *
   * @type {number}
   * @memberof VideoListRetrieve
   */
  id: number;
  /**
   *
   * @type {RatingRetrieve}
   * @memberof VideoListRetrieve
   */
  rating: RatingRetrieve;
  /**
   *
   * @type {number}
   * @memberof VideoListRetrieve
   */
  status: number;
  /**
   *
   * @type {string}
   * @memberof VideoListRetrieve
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof VideoListRetrieve
   */
  video_url: string | null;
}
