/* tslint:disable */
/* eslint-disable */
/**
 * BSS Request Manager API
 * REST API for Workflow Support System for managing video shooting, filming and live streaming requests of Budavári Schönherz Stúdió.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: kecskemety.oliver@simonyi.bme.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface VideoAdminSearch
 */
export interface VideoAdminSearch {
  /**
   *
   * @type {number}
   * @memberof VideoAdminSearch
   */
  avg_rating: number;
  /**
   *
   * @type {number}
   * @memberof VideoAdminSearch
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof VideoAdminSearch
   */
  last_aired: string;
  /**
   *
   * @type {number}
   * @memberof VideoAdminSearch
   */
  length: number;
  /**
   *
   * @type {string}
   * @memberof VideoAdminSearch
   */
  request_start_datetime: string;
  /**
   *
   * @type {number}
   * @memberof VideoAdminSearch
   */
  status: number;
  /**
   *
   * @type {boolean}
   * @memberof VideoAdminSearch
   */
  status_by_admin: boolean;
  /**
   *
   * @type {string}
   * @memberof VideoAdminSearch
   */
  title: string;
}
