/* tslint:disable */
/* eslint-disable */
/**
 * BSS Request Manager API
 * REST API for Workflow Support System for managing video shooting, filming and live streaming requests of Budavári Schönherz Stúdió.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kecskemety.oliver@simonyi.bme.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from '../base';
// @ts-ignore
import { TokenObtainPairOAuth2Request } from '../models';
// @ts-ignore
import { TokenObtainResponse } from '../models';
// @ts-ignore
import { TokenRefresh } from '../models';
// @ts-ignore
import { TokenRefreshRequest } from '../models';
/**
 * LoginApi - axios parameter creator
 * @export
 */
export const LoginApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
     * @param {TokenRefreshRequest} tokenRefreshRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    loginRefreshCreate: async (
      tokenRefreshRequest: TokenRefreshRequest,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'tokenRefreshRequest' is not null or undefined
      assertParamExists(
        'loginRefreshCreate',
        'tokenRefreshRequest',
        tokenRefreshRequest,
      );
      const localVarPath = `/api/v1/login/refresh`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        tokenRefreshRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {TokenObtainPairOAuth2Request} tokenObtainPairOAuth2Request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    loginSocialCreate: async (
      tokenObtainPairOAuth2Request: TokenObtainPairOAuth2Request,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'tokenObtainPairOAuth2Request' is not null or undefined
      assertParamExists(
        'loginSocialCreate',
        'tokenObtainPairOAuth2Request',
        tokenObtainPairOAuth2Request,
      );
      const localVarPath = `/api/v1/login/social`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication tokenAuth required
      await setApiKeyToObject(
        localVarHeaderParameter,
        'Authorization',
        configuration,
      );

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        tokenObtainPairOAuth2Request,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * LoginApi - functional programming interface
 * @export
 */
export const LoginApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = LoginApiAxiosParamCreator(configuration);
  return {
    /**
     * Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
     * @param {TokenRefreshRequest} tokenRefreshRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async loginRefreshCreate(
      tokenRefreshRequest: TokenRefreshRequest,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenRefresh>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.loginRefreshCreate(
          tokenRefreshRequest,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {TokenObtainPairOAuth2Request} tokenObtainPairOAuth2Request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async loginSocialCreate(
      tokenObtainPairOAuth2Request: TokenObtainPairOAuth2Request,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<TokenObtainResponse>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.loginSocialCreate(
          tokenObtainPairOAuth2Request,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * LoginApi - factory interface
 * @export
 */
export const LoginApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = LoginApiFp(configuration);
  return {
    /**
     * Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
     * @param {TokenRefreshRequest} tokenRefreshRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    loginRefreshCreate(
      tokenRefreshRequest: TokenRefreshRequest,
      options?: any,
    ): AxiosPromise<TokenRefresh> {
      return localVarFp
        .loginRefreshCreate(tokenRefreshRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {TokenObtainPairOAuth2Request} tokenObtainPairOAuth2Request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    loginSocialCreate(
      tokenObtainPairOAuth2Request: TokenObtainPairOAuth2Request,
      options?: any,
    ): AxiosPromise<TokenObtainResponse> {
      return localVarFp
        .loginSocialCreate(tokenObtainPairOAuth2Request, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * LoginApi - object-oriented interface
 * @export
 * @class LoginApi
 * @extends {BaseAPI}
 */
export class LoginApi extends BaseAPI {
  /**
   * Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
   * @param {TokenRefreshRequest} tokenRefreshRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LoginApi
   */
  public loginRefreshCreate(
    tokenRefreshRequest: TokenRefreshRequest,
    options?: AxiosRequestConfig,
  ) {
    return LoginApiFp(this.configuration)
      .loginRefreshCreate(tokenRefreshRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {TokenObtainPairOAuth2Request} tokenObtainPairOAuth2Request
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LoginApi
   */
  public loginSocialCreate(
    tokenObtainPairOAuth2Request: TokenObtainPairOAuth2Request,
    options?: AxiosRequestConfig,
  ) {
    return LoginApiFp(this.configuration)
      .loginSocialCreate(tokenObtainPairOAuth2Request, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
