/* tslint:disable */
/* eslint-disable */
/**
 * BSS Request Manager API
 * REST API for Workflow Support System for managing video shooting, filming and live streaming requests of Budavári Schönherz Stúdió.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kecskemety.oliver@simonyi.bme.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from '../base';
// @ts-ignore
import { TokenBlacklistRequest } from '../models';
/**
 * LogoutApi - axios parameter creator
 * @export
 */
export const LogoutApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Takes a token and blacklists it.
     * @param {TokenBlacklistRequest} tokenBlacklistRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logoutCreate: async (
      tokenBlacklistRequest: TokenBlacklistRequest,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'tokenBlacklistRequest' is not null or undefined
      assertParamExists(
        'logoutCreate',
        'tokenBlacklistRequest',
        tokenBlacklistRequest,
      );
      const localVarPath = `/api/v1/logout`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication tokenAuth required
      await setApiKeyToObject(
        localVarHeaderParameter,
        'Authorization',
        configuration,
      );

      // authentication jwtAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        tokenBlacklistRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * LogoutApi - functional programming interface
 * @export
 */
export const LogoutApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = LogoutApiAxiosParamCreator(configuration);
  return {
    /**
     * Takes a token and blacklists it.
     * @param {TokenBlacklistRequest} tokenBlacklistRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async logoutCreate(
      tokenBlacklistRequest: TokenBlacklistRequest,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.logoutCreate(
        tokenBlacklistRequest,
        options,
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * LogoutApi - factory interface
 * @export
 */
export const LogoutApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = LogoutApiFp(configuration);
  return {
    /**
     * Takes a token and blacklists it.
     * @param {TokenBlacklistRequest} tokenBlacklistRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logoutCreate(
      tokenBlacklistRequest: TokenBlacklistRequest,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .logoutCreate(tokenBlacklistRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * LogoutApi - object-oriented interface
 * @export
 * @class LogoutApi
 * @extends {BaseAPI}
 */
export class LogoutApi extends BaseAPI {
  /**
   * Takes a token and blacklists it.
   * @param {TokenBlacklistRequest} tokenBlacklistRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LogoutApi
   */
  public logoutCreate(
    tokenBlacklistRequest: TokenBlacklistRequest,
    options?: AxiosRequestConfig,
  ) {
    return LogoutApiFp(this.configuration)
      .logoutCreate(tokenBlacklistRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
