# Generated by Django 5.0.1 on 2024-01-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ban",
            name="reason",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
