# Generated by Django 5.0.2 on 2024-07-07 23:46

from django.conf import settings
from django.db import migrations, models

import common.models


def set_default_creator_to_ban(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Ban = apps.get_model("common", "Ban")
    if Ban.objects.filter(creator__isnull=True).exists():
        sentinel_user = User.objects.get_or_create(
            username="deleted",
            defaults={"first_name": "Felhasználó", "last_name": "Törölt"},
        )[0]
        Ban.objects.filter(creator__isnull=True).update(creator=sentinel_user)


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_ban_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(set_default_creator_to_ban),
        migrations.AlterField(
            model_name="ban",
            name="creator",
            field=models.ForeignKey(
                on_delete=models.SET(common.models.get_sentinel_user),
                related_name="ban_creator",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
