name: Frontend CI - Admin Dashboard

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
    paths:
      - 'frontend-admin/**'
      - '.github/workflows/frontend-admin.yml'

permissions:
  contents: read

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/frontend-base-workflow.yml
    with:
      working-directory: 'frontend-admin'
